language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

script: phpunit tests

notifications:
    email:
        recipients:
            - support@oaklibrary.com
        on_success: change
        on_failure: always
